import PyQt6.QtWidgets as QtW
from Editors.SpriteEditor.map_attributes import MAP_FORMATS

# Top-level spritemap saver
def save_mappings(editor, path):
    # Map version (1 = Sonic 1, 2 = Sonic 2, 3 = Sonic 3K)
    map_version = editor.map_dropdown.currentIndex() + 1

    if path.suffix.lower() == '.asm':
        save_mappings_asm(editor, path, map_version)
    else:
        save_mappings_bin(editor, path, map_version)

def save_mappings_asm(editor, path, map_version):
    # Retrieve Mapping Label name from the input box
    map_label = editor.map_name_input.text()
    if map_label == '':
        stem = path.stem.split(' ', 1)[0][:8]
        map_label = f"Map_{stem}"

    # Generate comment header for ASM files
    lines = []

    # Prompt user for a description
    description, ok = QtW.QInputDialog.getText(
        editor, "Sprite Description", "Enter a name for the new sprite build:", text="New Sprite"
    )

    # Apply description to the "title"
    if not ok or not description.strip():
        description = ""
    else:
        description = " - " + description.strip()

    lines.append("; ---------------------------------------------------------------------------")
    lines.append(f"; Sprite mappings{description}")
    lines.append("; Generated by Sonic Triad Studio")
    lines.append("; ---------------------------------------------------------------------------")

    # Check for MapMacros saving
    if editor.macro_cb.isChecked():
        save_mappings_macro(editor, path, map_label, lines)
        return

    # Extract format attributes dynamically
    map_format = MAP_FORMATS[map_version]
    header_size = map_format['header_size']
    attr_bytes = map_format['attr_bytes']
    x_bytes = map_format['x_bytes']

    # Header / Pointer Table
    lines.append(f"{map_label}:")
    for _i in range(len(editor.map_frames)):
        lines.append(f"\tdc.w {editor.frame_labels[_i]}-{map_label}")

    lines.append("")

    # Frame Definitions
    for _i, frame in enumerate(editor.map_frames):
        # Frame header: Label + (1-byte vs 2-byte declaration)
        pieces = frame.get('pieces', frame) if isinstance(frame, dict) else frame
        header_cmd = "dc.b" if header_size == 1 else "dc.w"
        lines.append(f"{editor.frame_labels[_i]}:\t{header_cmd} {len(pieces)}")

        for piece in pieces:
            attrs = get_piece_attributes(piece)
            y_hex = f"${attrs['y'] & 0xFF:02X}"
            size_hex = f"${attrs['size'] & 0xFF:02X}"

            # Sonic 1 style (1-byte X offset & single dc.b line)
            if x_bytes == 1 and attr_bytes == 2:
                t_hi = f"${(attrs['art_tile'] >> 8) & 0xFF:02X}"
                t_lo = f"${attrs['art_tile'] & 0xFF:02X}"
                x_hex = f"${attrs['x'] & 0xFF:02X}"
                lines.append(f"\tdc.b {y_hex}, {size_hex}, {t_hi}, {t_lo}, {x_hex}")

            # Word-aligned formats (Sonic 2 & Sonic 3K)
            else:
                lines.append(f"\tdc.b {y_hex}, {size_hex}")

                if attr_bytes == 4:  # Sonic 2 2P dual-tile attributes
                    t1_hex = f"${attrs['art_tile']:04X}"
                    t2_hex = f"${attrs['art_tile_2p']:04X}"
                    lines.append(f"\tdc.w ${t1_hex}, ${t2_hex}")
                else:  # Sonic 3K single tile attribute word
                    t_hex = f"${attrs['art_tile']:04X}"
                    lines.append(f"\tdc.w ${t_hex}")

                x_hex = f"${attrs['x'] & 0xFFFF:04X}"
                lines.append(f"\tdc.w ${x_hex}")

        lines.append("")

    lines.append("\teven")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

def save_mappings_macro(editor, path, map_label, lines):
    # Header / Pointer Table
    lines.append(f"{map_label}:\tmappingsTable")
    for _i in range(len(editor.map_frames)):
        lines.append(f"\tmappingsTableEntry.w\t{editor.frame_labels[_i]}")

    lines.append("")

    # Frame Definitions
    for _i, frame in enumerate(editor.map_frames):
        pieces = frame.get('pieces', frame) if isinstance(frame, dict) else frame
        frame_label = editor.frame_labels[_i]
        lines.append(f"{frame_label}:\tspriteHeader")
        for piece in pieces:
            attrs = get_piece_attributes(piece)
            lines.append(
                f"\tspritePiece {attrs['x']}, {attrs['y']}, {attrs['wid']}, {attrs['hgt']}, "
                f"${attrs['tile']:X}, {attrs['x_flip']}, {attrs['y_flip']}, {attrs['palette']}, {attrs['priority']}"
            )
        lines.append(f"{frame_label}_End")

        lines.append("")

    # Leave at the end of the file
    lines.append("\teven")
    lines.append("")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

def save_mappings_bin(editor, path, map_version):
    map_format = MAP_FORMATS[map_version]
    header_size = map_format['header_size']
    attr_bytes = map_format['attr_bytes']
    x_bytes = map_format['x_bytes']

    num_frames = len(editor.map_frames)
    offsets = []
    frame_data_list = []
    current_offset = num_frames * 2

    for frame in editor.map_frames:
        pieces = frame.get('pieces', frame) if isinstance(frame, dict) else frame
        offsets.append(current_offset)
        buffer = bytearray()

        # Write frame header piece count using format header_size
        buffer.extend(len(pieces).to_bytes(header_size, byteorder='big'))

        for piece in pieces:
            attrs = get_piece_attributes(piece)
            buffer.append(attrs['y'] & 0xFF)
            buffer.append(attrs['size'] & 0xFF)

            # Write tile attributes
            buffer.extend((attrs['art_tile'] & 0xFFFF).to_bytes(2, byteorder='big'))
            if attr_bytes == 4:
                buffer.extend((attrs['art_tile_2p'] & 0xFFFF).to_bytes(2, byteorder='big'))

            # Write X offset using format x_bytes
            buffer.extend((attrs['x'] & (0xFFFF if x_bytes == 2 else 0xFF)).to_bytes(x_bytes, byteorder='big'))

        frame_data_list.append(buffer)
        current_offset += len(buffer)

    full_data = bytearray()
    for off in offsets:
        full_data.extend(off.to_bytes(2, byteorder='big'))
    for buffer in frame_data_list:
        full_data.extend(buffer)

    with open(path, "wb") as f:
        f.write(full_data)

def get_piece_attributes(piece):
    # Pixel coordinates
    y = piece.get('y', 0)
    x = piece.get('x', 0)

    # Piece size
    wid, hgt = piece.get('width', 0), piece.get('height', 0)
    size = ((wid - 1) << 2) | (hgt - 1)

    tile = piece.get('tile', 0)
    palette = piece.get('palette', 0)
    x_flip = 1 if piece.get('x_flip', False) else 0
    y_flip = 1 if piece.get('y_flip', False) else 0
    priority = 1 if piece.get('priority', False) else 0

    # Construct VDP Art Tile word if not already present
    art_tile = ((priority & 1) << 15) | ((palette & 3) << 13) | ((y_flip & 1) << 12) | ((x_flip & 1) << 11) | (
                    tile & 0x07FF)

    # Sonic 2's 2P Art Tile word (Double-check this later)
    art_tile_2p = art_tile >> 1

    return {
        'y': y, 'x': x,
        'wid': wid, 'hgt': hgt, 'size': size,
        'tile': tile, 'palette': palette,
        'x_flip': x_flip, 'y_flip': y_flip, 'priority': priority,
        'art_tile': art_tile, 'art_tile_2p': art_tile_2p
    }
